# -*- coding: utf-8 -*-
"""Prueba_Codigo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-AEgo1dD0yq29kAfwZe9XEnNZloNK9Oy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
# %load_ext rpy2.ipython
import datetime
import seaborn as sns
from scipy.integrate import odeint
import cufflinks as cf
import plotly.offline as py
import scipy.integrate as spi

"""## Lectura de datos"""

covid = pd.read_csv('https://www.datos.gov.co/api/views/gt2j-8ykr/rows.csv?accessType=DOWNLOAD')
covid1 = covid.drop(['Código DIVIPOLA','País de procedencia', 'fecha reporte web', 'Codigo departamento', 'Codigo pais', 'Pertenencia etnica', 'Nombre grupo etnico'],axis=1) #eliminar columnas innecesarias
covid1['Fecha de notificación'] = pd.to_datetime(covid1['Fecha de notificación'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['Fecha de muerte'] = pd.to_datetime(covid1['Fecha de muerte'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['Fecha diagnostico'] = pd.to_datetime(covid1['Fecha diagnostico'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['Fecha recuperado'] = pd.to_datetime(covid1['Fecha recuperado'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['FIS'] = pd.to_datetime(covid1['FIS'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['Fecha diagnostico']=covid1['Fecha diagnostico'].fillna(method='ffill')

covid1['Sexo'] =covid1['Sexo'].apply(lambda x: str(x).upper())

sns.countplot(covid1['Sexo'])

covid1['Dif_Dias'] = covid1['Fecha de muerte'] - covid1['Fecha diagnostico']

covid1.groupby('Dif_Dias').size()

covid1['diff'] = covid1['Fecha de muerte'] - covid1['Fecha diagnostico']

covid1.groupby('diff').size()

"""3. Periodo de tiempo entre el diagnostico de la enfermedad y la recuperación del paciente"""

covid1['diff2'] = covid1['Fecha recuperado']- covid1['Fecha diagnostico']
covid1.groupby('diff2').size()

"""4. Cantidad de contagios por ciudad"""

covid1.groupby('Ciudad de ubicación').size().sort_values(ascending = False)

"""5. Promedio de edad de los casos por estada de gravedad"""

covid1.groupby('Estado')['Edad'].mean()

covid1.groupby('Estado')['Edad'].mean().plot.bar();

"""6. Cantidad de casos que se recuperan por tipo de atención (Hospital, Hospital UCI, casa ...)"""

covid1.groupby('atención').size()

covid1.groupby('atención').size().plot.bar();

"""Las ciudades que se estudiarán son Medellín, Bogotá, Cartagena de Indias y Barranquilla"""

covid2 = covid1[covid1['Ciudad de ubicación'].isin(['Medellín', 'Cali', 'Bogotá D.C.', 'Cartagena de Indias', 'Barranquilla'])]

"""## Cálculo de casos por semana y por día 
1. Fecha de inicio de sintomas
"""

covid2['contador'] = 1 # se creará un contador dado que los datos son cualitativos

total_FIS = covid2.groupby('FIS').sum()
total_FIS['contador'].describe()

total_FIS = covid2.groupby('FIS').sum()
total_FIS['FIS'] = total_FIS.index.tolist()

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

graficar(total_FIS['FIS'], total_FIS['contador'], 'FIS', 'contador')

total_diagnostico = covid2.groupby('Fecha diagnostico').sum()
total_diagnostico['contador'].describe()

total_diagnostico = covid2.groupby('Fecha diagnostico').sum()
total_diagnostico['Fecha diagnostico'] = total_diagnostico.index.tolist()

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

graficar(total_diagnostico['Fecha diagnostico'], total_diagnostico['contador'], 'Fecha diagnostico', 'contador')

"""Gráfico de dispersión casos diagnosticados con covid19"""

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

#graficar(total['semana diagnostico'], total['contador'], 'semana diagnostico', 'contador')

"""3. Fecha de muerte"""

#fallecidos = covid2[covid2['atención'].isin(['Fallecido'])] # se filtra por fallecidos

#fallecidos['semana fallecido'] = fallecidos['Fecha de muerte'].apply(lambda x : pd.to_datetime(str(x)).isocalendar()[1])

#total_fallecidos = fallecidos.groupby('semana fallecido').sum()
#total_fallecidos = total_fallecidos[[ "contador"]]
#total_fallecidos['semana fallecido'] = total_fallecidos.index.tolist()

total_fallecidos = covid2.groupby('Fecha de muerte').sum()
total_fallecidos['contador'].describe()

total_fallecidos = covid2.groupby('Fecha de muerte').sum()
total_fallecidos['Fecha de muerte'] = total_fallecidos.index.tolist()

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

graficar(total_fallecidos['Fecha de muerte'], total_fallecidos['contador'], 'Fecha de muerte', 'contador')

"""Gráfico de dispersión fallecidos por covid19"""

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

#graficar(total_fallecidos['semana fallecido'], total_fallecidos['contador'], 'semana fallecido', 'contador')

"""4. Fecha de recuperados"""

#recuperados = covid2[covid2['atención'].isin(['Recuperado'])]

#recuperados['semana recuperado'] = recuperados['Fecha recuperado'].apply(lambda x : pd.to_datetime(str(x)).isocalendar()[1]) # se agrega la semana por cada fecha de recuperado

#total_recuperados = recuperados.groupby('semana recuperado').sum()
#total_recuperados = total_recuperados[[ "contador"]]
#total_recuperados['semana recuperado'] = total_recuperados.index.tolist()

total_recuperados = covid2.groupby('Fecha recuperado').sum()
total_recuperados['contador'].describe()

total_recuperados = covid2.groupby('Fecha recuperado').sum()
total_recuperados['Fecha recuperado'] = total_recuperados.index.tolist()

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

graficar(total_recuperados['Fecha recuperado'], total_recuperados['contador'], 'Fecha recuperado', 'contador')

"""Gráfico de dispersión recuperados por covid19"""

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

#graficar(total_recuperados2['semana recuperado'], total_recuperados2['contador'], 'semana recuperado', 'contador')

#covid1[covid1['Fecha recuperado'].isnull() & covid1['Fecha de muerte'].isnull()]

fallecidos = covid2[covid2['atención'].isin(['Fallecido'])] # se filtra por fallecidos

fallecidos['semana fallecido'] = fallecidos['Fecha de muerte'].apply(lambda x : pd.to_datetime(str(x)).isocalendar()[1])

total_fallecidos = fallecidos.groupby('semana fallecido').sum()
total_fallecidos = total_fallecidos[[ "contador"]]
total_fallecidos['semana fallecido'] = total_fallecidos.index.tolist()

total_fallecidos = covid2.groupby('Fecha de muerte').sum()
total_fallecidos['contador'].describe()

total_fallecidos = covid2.groupby('Fecha de muerte').sum()
total_fallecidos['Fecha de muerte'] = total_fallecidos.index.tolist()



total = covid2.groupby('Fecha diagnostico').sum()

total['casos confirmados'] = total['contador']
#print(total.loc[:,'casos confirmados'])
total_recuperados = covid2.groupby('Fecha recuperado').sum()
total_recuperados['contador'].describe()

total_recuperados = covid2.groupby('Fecha recuperado').sum()
total_recuperados['Fecha recuperado'] = total_recuperados.index.tolist()

total_recuperados['Fecha'] = total_recuperados['Fecha recuperado']
total_recuperados['Recuperados'] = total_recuperados['contador']
total_diagnostico['Fecha'] = total_diagnostico['Fecha diagnostico']
total_diagnostico['Casos confirmados'] = total['contador']
total_fallecidos['Fecha'] = total_fallecidos['Fecha de muerte']
total_fallecidos['Fallecidos'] = total_fallecidos['contador']

parcial = pd.merge(total_diagnostico, total_recuperados[['Fecha', 'Recuperados']], on='Fecha', how ='left')
Modelo = pd.merge(parcial, total_fallecidos[['Fecha', 'Fallecidos']], on='Fecha', how='left')
Modelo = Modelo[['Fecha', 'Casos confirmados', 'Recuperados', 'Fallecidos']]
Modelo = Modelo.fillna(0) 
población = 14832981

Modelo['Población'] = población

Modelo['Casos confirmados acumulados']= np.cumsum(Modelo['Casos confirmados'])

Modelo['susceptibles calculados'] = Modelo['Población'] - Modelo['Casos confirmados acumulados']

Modelo['Recuperados acumulados']= np.cumsum(Modelo['Recuperados'])
Modelo['Fallecidos acumulados']= np.cumsum(Modelo['Fallecidos'])
Modelo['Activos calculados'] = Modelo['Casos confirmados acumulados'] - Modelo['Fallecidos acumulados'].fillna(0) - Modelo['Recuperados acumulados'].fillna(0)

"""1. Cálculo tasa casos nuevos"""

Modelo['Casos activos'] = Modelo['Activos calculados'].shift(1)

def f(row):
    if row['Activos calculados'] == 1:
        tasa_contagio = 0
    else:
        tasa_contagio = (row['Casos confirmados'] /row['Casos activos'])
    return tasa_contagio
Modelo['tasa contagio'] = Modelo.apply(f, axis=1)

"""2. Cálculo tasa recuperados"""

def f(row):
    if row['Activos calculados'] == 1:
        tasa_recuperado = 0
    else:
        tasa_recuperado = (row['Recuperados'] /row['Casos activos'])
    return tasa_recuperado
Modelo['tasa recuperado'] = Modelo.apply(f, axis=1)

"""3. Cálculo tasa fallecidos"""

def f(row):
    if row['Activos calculados'] == 1:
        tasa_fallecidos = 0
    else:
        tasa_fallecidos = (row['Fallecidos'] /row['Casos activos'])
    return tasa_fallecidos
Modelo['tasa fallecidos'] = Modelo.apply(f, axis=1)

Modelo['Mediamovil_contagio'] = Modelo['tasa contagio'].rolling(window=5,center=False).mean()
Modelo['Mediamovil_recuperado'] = Modelo['tasa recuperado'].rolling(window=5,center=False).mean()
Modelo['Mediamovil_fallecido'] = Modelo['tasa fallecidos'].rolling(window=5,center=False).mean()

"""#Modelo SIR"""



beta = Modelo.iloc[-1,-3]
gamma = Modelo.iloc[-1,-2]
tetha = Modelo.iloc[-1,-1]

"""poner formulas y texto"""

#N, beta,gamma = 14832981, 0.067192, 0.027277

"""##Definición de parámetros"""

#Población total
N = población
#Valores iniciales de personas infectadas y personas que se recuperan
I0 = Modelo.iloc[-1,-7]
R0 = Modelo.iloc[-1, -8]
#Población susceptible
S0= Modelo.iloc[-1,6]

#t = np.linspace(0, 21, 21) # corto plazo

#Valores iniciales de personas infectadas y personas que se recuperan
TS=1.0
ND = 90.0
I0 = Modelo.iloc[-1,-7]
R0 = Modelo.iloc[-1, -8]
#Población susceptible
S0= Modelo.iloc[-1,6]
INPUT = (S0, I0, 0.0)

def diff_eqs(INP,t):  
    Y=np.zeros((3))
    V = INP
    #Las ecuaciones diferenciales
    Y[0] = - beta * V[0] * V[1]
    Y[1] = beta * V[0] * V[1] - gamma * V[1]
    Y[2] = gamma * V[1]
    return Y 

t_start = 0.0; t_end = ND; t_inc = TS
t_range = np.arange(t_start, t_end+t_inc, t_inc)
RES = spi.odeint(diff_eqs,INPUT,t_range)

plt.plot(RES[:,0]*N, '-g', label='Susceptibles')
plt.plot(RES[:,2]*N, '-k', label='Recuperados')
plt.plot(RES[:,1]*N, '-r', label='Infectados')
plt.legend(loc=0)
plt.title('Modelo SIR')
plt.xlabel('Tiempo')
plt.show()

import pandas as pd
import numpy as np

"""n = parcial.shape[0]
val = pd.DataFrame(list(range(1,n+1)))

parcial = pd.merge(total_diagnostico, val,total_recuperados[['Fecha', 'Recuperados']])
print(parcial)
"""

parcial = pd.merge(total_diagnostico, total_recuperados[['Fecha', 'Recuperados']], on='Fecha', how ='left')

n = parcial.shape[0]
val = pd.DataFrame(range(1,n+1))

parcial2 = parcial.assign(Tiempo = val)
#X = np.array(parcial2['Tiempo']).reshape(-1,1)
#y = np.array(parcial2['Casos confirmados'])

dat = parcial2
serie = parcial2['Casos confirmados']
dat_ma = serie.rolling(5).mean()
dat['Prod_Movil'] = dat_ma
plot = dat[['Casos confirmados', 'Prod_Movil']].plot(figsize=(10, 8), fontsize=12)

for col in Modelo.columns:
    fig = data.plot.bar(y=col).get_figure().savefig('figs/' + col + '.png')