# -*- coding: utf-8 -*-
"""Trabajo final Analítica Predictiva

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OTriMr1Bn6xvIvrw1Yz4lS9wz9LogEvP
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
# %load_ext rpy2.ipython
import datetime
import seaborn as sns
from scipy.integrate import odeint
import cufflinks as cf
import plotly.offline as py
import scipy.integrate as spi
from statsmodels.tsa.arima_model import ARIMA
from fbprophet import Prophet
from fbprophet.diagnostics import performance_metrics
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import matplotlib.pyplot as plt

"""## Lectura de datos"""

covid = pd.read_csv('https://www.datos.gov.co/api/views/gt2j-8ykr/rows.csv?accessType=DOWNLOAD')

"""# Limpieza de datos
1. Eliminación de columnas.
"""

covid1 = covid.drop(['Código DIVIPOLA','País de procedencia', 'fecha reporte web', 'Codigo departamento', 'Codigo pais', 'Pertenencia etnica', 'Nombre grupo etnico'],axis=1) #eliminar columnas innecesarias

"""2. Corrección de errores en la calidad de los datos. Eliminar hora de la fecha"""

covid1['Fecha de notificación'] = pd.to_datetime(covid1['Fecha de notificación'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['Fecha de muerte'] = pd.to_datetime(covid1['Fecha de muerte'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['Fecha diagnostico'] = pd.to_datetime(covid1['Fecha diagnostico'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['Fecha recuperado'] = pd.to_datetime(covid1['Fecha recuperado'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['FIS'] = pd.to_datetime(covid1['FIS'], format='%Y-%m-%d %H:%M:%S', errors='coerce')

covid1['Fecha diagnostico']=covid1['Fecha diagnostico'].fillna(method='ffill') # a cada fecha vacía se ingresa la fecha del caso anterior

"""#Analítica de datos
El objetivo es tener un mayor conocimiento y entendimiento de los datos y su comportamiento. Así como también identificar patrones o situaciones importantes a tener en cuenta.

1. Cantidad de casos por sexo
"""

covid1['Sexo'] =covid1['Sexo'].apply(lambda x: str(x).upper())

sns.countplot(covid1['Sexo'])

"""2. Periodo de tiempo entre que se diagnostica la enfermedad y la persona muere"""

covid1['diff'] = covid1['Fecha de muerte'] - covid1['Fecha diagnostico']

covid1.groupby('diff').size()

"""3. Periodo de tiempo entre el diagnostico de la enfermedad y la recuperación del paciente"""

covid1['diff2'] = covid1['Fecha recuperado']- covid1['Fecha diagnostico']
covid1.groupby('diff2').size()

"""4. Cantidad de contagios por ciudad"""

covid1.groupby('Ciudad de ubicación').size().sort_values(ascending = False)

"""5. Promedio de edad de los casos por estada de gravedad"""

covid1.groupby('Estado')['Edad'].mean()

covid1.groupby('Estado')['Edad'].mean().plot.bar();

"""6. Cantidad de casos que se recuperan por tipo de atención (Hospital, Hospital UCI, casa ...)"""

covid1.groupby('atención').size()

covid1.groupby('atención').size().plot.bar();

"""Las ciudades que se estudiarán son Medellín, Bogotá, Cartagena de Indias y Barranquilla"""

covid2 = covid1[covid1['Ciudad de ubicación'].isin(['Medellín', 'Cali', 'Bogotá D.C.', 'Cartagena de Indias', 'Barranquilla'])]

"""# Cálculo de casos por semana y por día 
1. Fecha de inicio de sintomas
"""

covid2['contador'] = 1 # se creará un contador dado que los datos son cualitativos

total_FIS = covid2.groupby('FIS').sum()
total_FIS['contador'].describe()

total_FIS = covid2.groupby('FIS').sum()
total_FIS['FIS'] = total_FIS.index.tolist()

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

graficar(total_FIS['FIS'], total_FIS['contador'], 'FIS', 'contador')

"""2. Fecha de diagnostico"""

#covid2['semana diagnostico'] = covid2['Fecha diagnostico'].apply(lambda x : pd.to_datetime(str(x)).isocalendar()[1]) # se agrega el número de la semana del año por cada fecha

#total = covid2.groupby('semana diagnostico').sum()
#total = total[[ "contador"]]
#total['semana diagnostico'] = total.index.tolist()

total_diagnostico = covid2.groupby('Fecha diagnostico').sum()
total_diagnostico['contador'].describe()

total_diagnostico = covid2.groupby('Fecha diagnostico').sum() 
total_diagnostico['Fecha diagnostico'] = total_diagnostico.index.tolist()

"""Gráfico de dispersión casos diagnosticados con covid19"""

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

graficar(total_diagnostico['Fecha diagnostico'], total_diagnostico['contador'], 'Fecha diagnostico', 'contador')

"""3. Fecha de muerte"""

#fallecidos = covid2[covid2['atención'].isin(['Fallecido'])] # se filtra por fallecidos

#fallecidos['semana fallecido'] = fallecidos['Fecha de muerte'].apply(lambda x : pd.to_datetime(str(x)).isocalendar()[1])

#total_fallecidos = fallecidos.groupby('semana fallecido').sum()
#total_fallecidos = total_fallecidos[[ "contador"]]
#total_fallecidos['semana fallecido'] = total_fallecidos.index.tolist()

total_fallecidos = covid2.groupby('Fecha de muerte').sum()
total_fallecidos['contador'].describe()

total_fallecidos = covid2.groupby('Fecha de muerte').sum()
total_fallecidos['Fecha de muerte'] = total_fallecidos.index.tolist()

"""Gráfico de dispersión fallecidos por covid19"""

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

graficar(total_fallecidos['Fecha de muerte'], total_fallecidos['contador'], 'Fecha de muerte', 'contador')

"""4. Fecha de recuperados"""

#recuperados = covid2[covid2['atención'].isin(['Recuperado'])]

#recuperados['semana recuperado'] = recuperados['Fecha recuperado'].apply(lambda x : pd.to_datetime(str(x)).isocalendar()[1]) # se agrega la semana por cada fecha de recuperado

#total_recuperados = recuperados.groupby('semana recuperado').sum()
#total_recuperados = total_recuperados[[ "contador"]]
#total_recuperados['semana recuperado'] = total_recuperados.index.tolist()

total_recuperados = covid2.groupby('Fecha recuperado').sum()
total_recuperados['contador'].describe()

total_recuperados = covid2.groupby('Fecha recuperado').sum()
total_recuperados['Fecha recuperado'] = total_recuperados.index.tolist()

"""Gráfico de dispersión recuperados por covid19"""

import matplotlib.pyplot as plt

def graficar(x, y, labelX, labelY):
    plt.figure()
    plt.scatter(x, y)
    plt.xlabel(labelX)
    plt.ylabel(labelY)
    plt.show()

graficar(total_recuperados['Fecha recuperado'], total_recuperados['contador'], 'Fecha recuperado', 'contador')

"""#Modelo SIR"""

total = covid2.groupby('Fecha diagnostico').sum()
total['casos confirmados'] = total['contador']
total

total_recuperados['Fecha'] = total_recuperados['Fecha recuperado']
total_recuperados['Recuperados'] = total_recuperados['contador']
total_diagnostico['Fecha'] = total_diagnostico['Fecha diagnostico']
total_diagnostico['Casos confirmados'] = total['contador']
total_fallecidos['Fecha'] = total_fallecidos['Fecha de muerte']
total_fallecidos['Fallecidos'] = total_fallecidos['contador']
parcial = pd.merge(total_diagnostico, total_recuperados[['Fecha', 'Recuperados']], on='Fecha', how ='left')
Modelo = pd.merge(parcial, total_fallecidos[['Fecha', 'Fallecidos']], on='Fecha', how='left')
Modelo = Modelo[['Fecha', 'Casos confirmados', 'Recuperados', 'Fallecidos']]
Modelo = Modelo.fillna(0) 
Modelo

"""Total Población en cada ciudad: Bogota	7.743.955
Medellín	2.533.424
Cali	2.252.616
Cartagena	1.028.736
Barranquilla	1.274.250

N = 14.832.981 Población total
"""

población = 14832981

Modelo['Población'] = población

Modelo['Casos confirmados acumulados']= np.cumsum(Modelo['Casos confirmados'])
Modelo

Modelo['susceptibles calculados'] = Modelo['Población'] - Modelo['Casos confirmados acumulados']
 Modelo

"""##Cálculo de tasas de contagio, recuperados y fallecidos"""

Modelo['Recuperados acumulados']= np.cumsum(Modelo['Recuperados'])
Modelo['Fallecidos acumulados']= np.cumsum(Modelo['Fallecidos'])
Modelo['Activos calculados'] = Modelo['Casos confirmados acumulados'] - Modelo['Fallecidos acumulados'].fillna(0) - Modelo['Recuperados acumulados'].fillna(0)

"""1. Cálculo tasa casos nuevos"""

Modelo['Casos activos'] = Modelo['Activos calculados'].shift(1)

def f(row):
    if row['Activos calculados'] == 1:
        tasa_contagio = 0
    else:
        tasa_contagio = (row['Casos confirmados'] /row['Casos activos'])
    return tasa_contagio
Modelo['tasa contagio'] = Modelo.apply(f, axis=1)

"""2. Cálculo tasa recuperados"""

def f(row):
    if row['Activos calculados'] == 1:
        tasa_recuperado = 0
    else:
        tasa_recuperado = (row['Recuperados'] /row['Casos activos'])
    return tasa_recuperado
Modelo['tasa recuperado'] = Modelo.apply(f, axis=1)

"""3. Cálculo tasa fallecidos"""

def f(row):
    if row['Activos calculados'] == 1:
        tasa_fallecidos = 0
    else:
        tasa_fallecidos = (row['Fallecidos'] /row['Casos activos'])
    return tasa_fallecidos
Modelo['tasa fallecidos'] = Modelo.apply(f, axis=1)

Modelo['Mediamovil_contagio'] = Modelo['tasa contagio'].rolling(window=5,center=False).mean()
Modelo['Mediamovil_recuperado'] = Modelo['tasa recuperado'].rolling(window=5,center=False).mean()
Modelo['Mediamovil_fallecido'] = Modelo['tasa fallecidos'].rolling(window=5,center=False).mean()

"""##Definición de parámetros"""

beta = Modelo.iloc[-1,-3]
gamma = Modelo.iloc[-1,-2]
tetha = Modelo.iloc[-1,-1]

"""poner formulas y texto"""

"""##Definición de parámetros"""

#Población total
N = población
#Valores iniciales de personas infectadas y personas que se recuperan
I0 = Modelo.iloc[-1,-7]
R0 = Modelo.iloc[-1, -8]
#Población susceptible
S0= Modelo.iloc[-1,6]

#t = np.linspace(0, 21, 21) # corto plazo

#Valores iniciales de personas infectadas y personas que se recuperan
TS=1.0
ND = 90.0
I0 = Modelo.iloc[-1,-7]
R0 = Modelo.iloc[-1, -8]
#Población susceptible
S0= Modelo.iloc[-1,6]
INPUT = (S0, I0, 0.0)

def diff_eqs(INP,t):  
    Y=np.zeros((3))
    V = INP
    #Las ecuaciones diferenciales
    Y[0] = - beta * V[0] * V[1]
    Y[1] = beta * V[0] * V[1] - gamma * V[1]
    Y[2] = gamma * V[1]
    return Y 

t_start = 0.0; t_end = ND; t_inc = TS
t_range = np.arange(t_start, t_end+t_inc, t_inc)
RES = spi.odeint(diff_eqs,INPUT,t_range)

plt.plot(RES[:,0]*N, '-g', label='Susceptibles')
plt.plot(RES[:,2]*N, '-k', label='Recuperados')
plt.plot(RES[:,1]*N, '-r', label='Infectados')
plt.legend(loc=0)
plt.title('Modelo SIR')
plt.xlabel('Tiempo')
plt.show()

"""# Modelo con medias móviles"""

import pandas as pd
import numpy as np

parcial = pd.merge(total_diagnostico, total_recuperados[['Fecha', 'Recuperados']], on='Fecha', how ='left')

n = parcial.shape[0]
val = pd.DataFrame(range(1,n+1))

parcial2 = parcial.assign(Tiempo = val)
#X = np.array(parcial2['Tiempo']).reshape(-1,1)
#y = np.array(parcial2['Casos confirmados'])

#Resumen Global de Casos
n_datos = Modelo[['Casos confirmados', 'Recuperados', 'Fallecidos']]
resumen_comp = pd.DataFrame(n_datos.sum()).transpose()
resumen_comp.style.format("{:,.0f}")

"""1. Casos confirmados"""

dat = parcial2
serie = parcial2['Casos confirmados']
dat_ma = serie.rolling(5).mean()
dat['Prod_Movil'] = dat_ma
plot = dat[['Casos confirmados', 'Prod_Movil']].plot(figsize=(10, 8), fontsize=12)
plt.title("Serie de los casos confirmados modelado con promedio movil")

"""2. Recuperados"""

dat = parcial2
serie = parcial2['Recuperados']
dat_ma = serie.rolling(5).mean()
dat['Prod_Movil'] = dat_ma
plot = dat[['Recuperados', 'Prod_Movil']].plot(figsize=(10, 8), fontsize=12)
plt.title("Serie de las personas recuperadas modelado con promedio movil")

"""3. Fallecidos"""

dat = Modelo
serie = Modelo[['Fallecidos']]
dat_ma = serie.rolling(5).mean()
dat['Prod_Movil'] = dat_ma
plot = dat[['Fallecidos', 'Prod_Movil']].plot(figsize=(10, 8), fontsize=12)
plt.xlabel("Tiempo(Días)")
plt.ylabel("Casos Fallecidos")
plt.title("Serie de los casos Fallecidos modelado con promedio movil")

"""# Modelo Arima

1. Casos confirmados
"""

modelo = ARIMA(total_diagnostico['Casos confirmados'].iloc[1:], order=(1, 0, 0))  
resultados = modelo.fit(disp=-1)  
total_diagnostico['pronostico'] = resultados.fittedvalues  
plot = total_diagnostico[['Casos confirmados', 'pronostico']].plot(figsize=(10, 8))

"""2. Recuperados"""

modelo = ARIMA(total_recuperados['Recuperados'].iloc[1:], order=(1, 0, 0))  
resultados = modelo.fit(disp=-1)  
total_recuperados['pronostico'] = resultados.fittedvalues  
plot = total_recuperados[['Recuperados', 'pronostico']].plot(figsize=(10, 8))

"""3. Fallecidos"""

modelo = ARIMA(total_fallecidos['Fallecidos'].iloc[1:], order=(1, 0, 0))  
resultados = modelo.fit(disp=-1)  
total_fallecidos['pronostico'] = resultados.fittedvalues  
plot = total_fallecidos[['Fallecidos', 'pronostico']].plot(figsize=(10, 8))

"""# Modelo Prophet para predicción

## Corto plazo

Predicción a corto plazo casos nuevos
"""

def prediccion_corto(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_nuevos = prediccion_corto(total_diagnostico, 'Casos confirmados', dias)

"""Predicción a corto plazo casos recuperados"""

def prediccion_corto(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_recuperados = prediccion_corto(total_recuperados, 'Recuperados', dias)

"""Predicción a corto plazo casos fallecidos"""

def prediccion_corto(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_fallecidos = prediccion_corto(total_fallecidos, 'Fallecidos', dias)

"""## Mediano plazo

Predicción a mediano plazo casos nuevos
"""

def prediccion_mediano(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_nuevos = prediccion_mediano(total_diagnostico, 'Casos confirmados', dias)

"""Predicción a mediano plazo casos recuperados"""

def prediccion_mediano(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado',ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_recuperados = prediccion_mediano(total_recuperados, 'Recuperados', dias)

"""Predicción a mediano plazo casos fallecidos"""

def prediccion_mediano(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte',ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_fallecidos = prediccion_mediano(total_fallecidos, 'Fallecidos', dias)

"""Datos por ciudad"""

Medellin = covid2[covid2['Ciudad de ubicación'].isin(['Medellín'])]
Medellin_diagnostico = Medellin.groupby('Fecha diagnostico').sum() 
Medellin_diagnostico['Fecha diagnostico'] = Medellin_diagnostico.index.tolist()
Medellin_diagnostico['casos confirmados'] = Medellin_diagnostico['contador']
Medellin_diagnostico
Medellin_recuperado = Medellin.groupby('Fecha recuperado').sum() 
Medellin_recuperado['Fecha recuperado'] = Medellin_recuperado.index.tolist()
Medellin_recuperado['Recuperados'] = Medellin_recuperado['contador']
Medellin_recuperado
Medellin_fallecidos = Medellin.groupby('Fecha de muerte').sum() 
Medellin_fallecidos['Fecha de muerte'] = Medellin_fallecidos.index.tolist()
Medellin_fallecidos['Fallecidos'] = Medellin_fallecidos['contador']
Medellin_fallecidos

Bogota = covid2[covid2['Ciudad de ubicación'].isin(['Bogotá D.C.'])]
Bogota_diagnostico = Bogota.groupby('Fecha diagnostico').sum() 
Bogota_diagnostico['Fecha diagnostico'] = Bogota_diagnostico.index.tolist()
Bogota_diagnostico['casos confirmados'] = Bogota_diagnostico['contador']
Bogota_diagnostico
Bogota_recuperado = Bogota.groupby('Fecha recuperado').sum() 
Bogota_recuperado['Fecha recuperado'] = Bogota_recuperado.index.tolist()
Bogota_recuperado['Recuperados'] = Bogota_recuperado['contador']
Bogota_recuperado
Bogota_fallecidos = Bogota.groupby('Fecha de muerte').sum() 
Bogota_fallecidos['Fecha de muerte'] = Bogota_fallecidos.index.tolist()
Bogota_fallecidos['Fallecidos'] = Bogota_fallecidos['contador']

cali =  covid2[covid2['Ciudad de ubicación'].isin(['Cali'])]
cali_diagnostico = cali.groupby('Fecha diagnostico').sum() 
cali_diagnostico['Fecha diagnostico'] = cali_diagnostico.index.tolist()
cali_diagnostico['casos confirmados'] = cali_diagnostico['contador']
cali_diagnostico
cali_recuperado = cali.groupby('Fecha recuperado').sum() 
cali_recuperado['Fecha recuperado'] = cali_recuperado.index.tolist()
cali_recuperado['Recuperados'] = cali_recuperado['contador']
cali_recuperado
cali_fallecidos = cali.groupby('Fecha de muerte').sum() 
cali_fallecidos['Fecha de muerte'] = cali_fallecidos.index.tolist()
cali_fallecidos['Fallecidos'] = cali_fallecidos['contador']

Barranquilla =  covid2[covid2['Ciudad de ubicación'].isin(['Cali'])]
Barranquilla_diagnostico = Barranquilla.groupby('Fecha diagnostico').sum() 
Barranquilla_diagnostico['Fecha diagnostico'] = Barranquilla_diagnostico.index.tolist()
Barranquilla_diagnostico['casos confirmados'] = Barranquilla_diagnostico['contador']
Barranquilla_diagnostico
Barranquilla_recuperado = Barranquilla.groupby('Fecha recuperado').sum() 
Barranquilla_recuperado['Fecha recuperado'] = Barranquilla_recuperado.index.tolist()
Barranquilla_recuperado['Recuperados'] = Barranquilla_recuperado['contador']
Barranquilla_recuperado
Barranquilla_fallecidos = Barranquilla.groupby('Fecha de muerte').sum() 
Barranquilla_fallecidos['Fecha de muerte'] = Barranquilla_fallecidos.index.tolist()
Barranquilla_fallecidos['Fallecidos'] = Barranquilla_fallecidos['contador']

cartagena= covid2[covid2['Ciudad de ubicación'].isin(['Cartagena de Indias'])]
cartagena_diagnostico = cartagena.groupby('Fecha diagnostico').sum() 
cartagena_diagnostico['Fecha diagnostico'] = cartagena_diagnostico.index.tolist()
cartagena_diagnostico['casos confirmados'] = cartagena_diagnostico['contador']
cartagena_diagnostico
cartagena_recuperado = cartagena.groupby('Fecha recuperado').sum() 
cartagena_recuperado['Fecha recuperado'] = cartagena_recuperado.index.tolist()
cartagena_recuperado['Recuperados'] = cartagena_recuperado['contador']
cartagena_recuperado
cartagena_fallecidos = cartagena.groupby('Fecha de muerte').sum() 
cartagena_fallecidos['Fecha de muerte'] = cartagena_fallecidos.index.tolist()
cartagena_fallecidos['Fallecidos'] = cartagena_fallecidos['contador']

"""#Medellin  corto plazo

NUEVOS CASOS
"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 
  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_nuevos = prediccion_corto_cada_ciudad(Medellin_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_recuperados = prediccion_corto_cada_ciudad(Medellin_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_muertes = prediccion_corto_cada_ciudad(Medellin_fallecidos, 'Fallecidos', dias)

"""#Medellin Mediano plazo

NUEVOS CASOS
"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_nuevos = prediccion_medio_cada_ciudad(Medellin_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_recuperados = prediccion_medio_cada_ciudad(Medellin_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_muertes = prediccion_medio_cada_ciudad(Medellin_fallecidos, 'Fallecidos', dias)

"""#Bogota Corto plazo

NUEVOS CASOS
"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)
  return(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']], 
         d_prediction_plot,
         rdos,
         mse,
         mae)

dias = 21
prediccion_casos_nuevos_Bogota = prediccion_corto_cada_ciudad(Bogota_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_recuperados = prediccion_corto_cada_ciudad(Bogota_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_muertes = prediccion_corto_cada_ciudad(Bogota_fallecidos, 'Fallecidos', dias)

"""#Bogota mediano plazo

NUEVOS CASOS
"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_nuevos = prediccion_medio_cada_ciudad(Bogota_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_recuperados = prediccion_medio_cada_ciudad(Bogota_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_muertes = prediccion_medio_cada_ciudad(Bogota_fallecidos, 'Fallecidos', dias)

"""# Cali corto plazo

NUEVOS CASOS
"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)
  return(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']], 
         d_prediction_plot,
         rdos,
         mse,
         mae)

dias = 21
prediccion_casos_nuevos = prediccion_corto_cada_ciudad(cali_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_recuperados = prediccion_corto_cada_ciudad(cali_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_muertes = prediccion_corto_cada_ciudad(cali_fallecidos, 'Fallecidos', dias)

"""#Cali mediano plazo

NUEVOS CASOS
"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_nuevos = prediccion_medio_cada_ciudad(cali_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_recuperados = prediccion_medio_cada_ciudad(cali_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_muertes = prediccion_medio_cada_ciudad(cali_fallecidos, 'Fallecidos', dias)

"""#Barranquilla corto plazo

NUEVOS CASOS
"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)
  return(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']], 
         d_prediction_plot,
         rdos,
         mse,
         mae)

dias = 21
prediccion_casos_nuevos = prediccion_corto_cada_ciudad(Barranquilla_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_recuperados = prediccion_corto_cada_ciudad(Barranquilla_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_muertes = prediccion_corto_cada_ciudad(Barranquilla_fallecidos, 'Fallecidos', dias)

"""#Barranquilla mediano plazo

NUEVOS CASOS
"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_nuevos = prediccion_medio_cada_ciudad(Barranquilla_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_recuperados = prediccion_medio_cada_ciudad(Barranquilla_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_muertes = prediccion_medio_cada_ciudad(Barranquilla_fallecidos, 'Fallecidos', dias)

"""#Cartagena corto plazo

NUEVOS CASOS
"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 21 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)
  return(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']], 
         d_prediction_plot,
         rdos,
         mse,
         mae)

dias = 21
prediccion_casos_nuevos = prediccion_corto_cada_ciudad(cartagena_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_recuperados = prediccion_corto_cada_ciudad(cartagena_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_corto_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 21
prediccion_casos_muertes = prediccion_corto_cada_ciudad(cartagena_fallecidos, 'Fallecidos', dias)

"""#Cartagena mediano plazo

NUEVOS CASOS
"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha diagnostico', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha diagnostico', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_nuevos = prediccion_medio_cada_ciudad(cartagena_diagnostico, 'casos confirmados', dias)

"""RECUPERADOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha recuperado', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha recuperado', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_recuperados = prediccion_medio_cada_ciudad(cartagena_recuperado, 'Recuperados', dias)

"""FALLECIDOS"""

def prediccion_medio_cada_ciudad(df_covid, variable, dias):
  
 

  # Filtrado y cambio de nombre de columnas
  df_corto= df_covid[['Fecha de muerte', variable]]
  df_corto.columns = ["ds", "y"]


 # Ajuste del modelo
  ajuste_cor = Prophet(interval_width = 0.95)
  ajuste_cor.fit(df_corto)

  #Predicciones
  d_pred = ajuste_cor.make_future_dataframe(periods=dias) 
  d_prediction = ajuste_cor.predict(d_pred)
  print(d_prediction[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(10))

  # Gráfica de predicciones
  d_prediction_plot = ajuste_cor.plot(d_prediction, xlabel='Fecha de muerte', ylabel=variable.title() )
  ax = d_prediction_plot.gca()

    # Errores del modelo
  metrics_df = d_prediction.set_index('ds')[['yhat']].join(df_corto.set_index('ds').y).reset_index()
  metrics_df.dropna(inplace=True)
  rdos=r2_score(metrics_df.y, metrics_df.yhat)
  mse=mean_squared_error(metrics_df.y, metrics_df.yhat)
  mae=mean_absolute_error(metrics_df.y, metrics_df.yhat)

  print('La predicción para los próximos 90 días es:')
  print('El r2 es: ',rdos)
  print('El MSE es: ',mse)
  print('El MAE es: ',mae)

dias = 90
prediccion_casos_muertes = prediccion_medio_cada_ciudad(cartagena_fallecidos, 'Fallecidos', dias)